// Liste de tous les styles de musique
// Sources => Tags ID3, http://www.multimediasoft.com/amp3dj/help/index.html?amp3dj_00003e.htm

listeGenre = ["Blues",
              "ClassicRock",
              "Country",
              "Dance",
              "Disco",
              "Funk",
              "Grunge",
              "HipHop",
              "Jazz",
              "Metal",
              "NewAge",
              "Oldies",
              "Other",
              "Pop",
              "R&B",
              "Rap",
              "Reggae",
              "Rock",
              "Techno",
              "Industrial",
              "Alternative",
              "Ska",
              "DeathMetal",
              "Pranks",
              "Soundtrack",
              "EuroTechno",
              "Ambient",
              "TripHop",
              "Vocal",
              "Jazz+Funk",
              "Fusion",
              "Trance",
              "Classical",
              "Instrumental",
              "Acid",
              "House",
              "Game",
              "SoundClip",
              "Gospel",
              "Noise",
              "AlternativeRock",
              "Bass",
              "Soul",
              "Punk",
              "Space",
              "Meditative",
              "Instrumental Pop",
              "Instrumental Rock",
              "Ethnic",
              "Gothic",
              "Darkwave",
              "TechnoIndustrial",
              "Electronic",
              "PopFolk",
              "Eurodance",
              "Dream",
              "Southern Rock",
              "Comedy",
              "Cult",
              "Gangsta",
              "Top",
              "Christian Rap",
              "Pop/Funk",
              "Jungle",
              "NativeUS",
              "Cabaret",
              "NewWave",
              "Psychadelic",
              "Rave",
              "Showtunes",
              "Trailer",
              "LoFi",
              "Tribal",
              "AcidPunk",
              "AcidJazz",
              "Polka",
              "Retro",
              "Musical",
              "Rock&Roll",
              "HardRock",
              "Folk",
              "FolkRock",
              "National Folk",
              "Swing",
              "FastFusion",
              "Bebob",
              "Latin",
              "Revival",
              "Celtic",
              "Bluegrass",
              "Avantgarde",
              "GothicRock",
              "Progressive Rock",
              "Psychedelic Rock",
              "Symphonic Rock",
              "SlowRock",
              "BigBand",
              "Chorus",
              "Easy Listening",
              "Acoustic",
              "Humour",
              "Speech",
              "Chanson",
              "Opera",
              "Chamber Music",
              "Sonata",
              "Symphony",
              "BootyBass",
              "Primus",
              "Porn Groove",
              "Satire",
              "SlowJam",
              "Club",
              "Tango",
              "Samba",
              "Folklore",
              "Ballad",
              "Power Ballad",
              "Rhythmic Soul",
              "Freestyle",
              "Duet",
              "Punk Rock",
              "DrumSolo",
              "Acapella",
              "EuroHouse",
              "DanceHall",
              "Goa",
              "Drum&Bass",
              "ClubHouse",
              "Hardcore",
              "Terror",
              "Indie",
              "Brit Pop",
              "Negerpunk",
              "PolskPunk",
              "Beat",
              "Christian Gangsta Rap",
              "Heavy Metal",
              "Black Metal",
              "Crossover",
              "Contemporary Christian",
              "Christian Rock",
              "Merengue",
              "Salsa",
              "Thrash Metal",
              "Anime",
              "JPop",
              "Synthpop"];

listeGenreObject = new Array();

function Genre(code, description) {
	this.code = code;
	this.description = description;
}

for(var g in listeGenre) {
	listeGenreObject.push(new Genre(listeGenre[g], listeGenre[g]));
}

db.Genre.insert(listeGenreObject);

